(* expression that requires a block after it *)
expr_with_block =
    | if_expr
    | while_expr
    | switch_expr
    | def_block
    | block
    ;

if_expr = "if" expr block {"else" if_stmt} ["else" block];

block = "{" {stmt} [expr] "}";

stmt = 
    | assign_stmt
    | fun_decl
    | defer_stmt
    ;

var_decl_kind = "def" | "let" | "mut";

assign_stmt = [var_decl_kind] ident {"," [var_decl_kind] ident} [","] "=" expr {"," expr} [","] ";";

fun_params = ["def"] ident {"," ["def"] ident} [","] ":" expr

fun_signature = "fun" [ident] "(" fun_params {"," fun_params} [","] ")" [":" expr];

fun_decl = fun_signature block;